title: Pagina de Juanma
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://juanmaa211.github.io/

aux_links:
  Template Repository: https://www.youtube.com/channel/UC8rNKrqBxJqL9izOOMxBJtw



